todo/todoapp/urls.py
from todoapp import views
from django.urls import path
from . import views
app_name="todoapp"
urlpatterns = [
    path('',views.add,name='add'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:pk>/', views.update,name='update'),
    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.TaskUpdateView.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/)',views.TaskDeleteView.as_view(),name='cbvdelete'),

]

todo/todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]

todo/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()
    def __str__(self):
        return self.name

todo/todoapp/forms.py
from .models import Task
from django import forms


class Todoform(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name','priority','date']

todo/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from . models import Task
from . forms import Todoform
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView,DeleteView

class Tasklistview(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'

class TaskDetailview(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'

class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','age')

    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})
class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('cbvhome')











def add(request):
    task1 = Task.objects.all()
    if(request.method=="POST"):
        name=request.POST['task']
        priority=request.POST['priority']
        date=request.POST.get('date')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task1':task1})
# def details(request):
#
#     return render(request,'details.html')
def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def cancel(request):
    if request.method=='POST':
        return redirect('/')


def update(request,id):
    task = Task.objects.get(id=id)
    f = Todoform(request.POST or None,instance = task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html',{'f':f,'task':task})

todo/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todo/templates/delete.html
{%extends 'base.html' %}



{% block content %}

<form method="POST">
    {% csrf_token %}
    <p>Are you sure this task is done..?</p>
    <input type="submit" value="yes.!">
</form>

{% endblock %}

todo/templates/details.html
{% extends 'base.html' %}


{% block content %}

<div class="shadow card">
    <div class="card-body">
        <h5 class="card-title">{{task.name}}</h5>
        <p><b>{{task.priority}}</b></p>
        <p><b>{{task .update}}</b></p>
        <a class="btn btn-danger" href="{% url 'delete' task.id %}">Done</a>
        <a class="btn btn-success" href="{% url 'update' task.id %}">Update</a>
    </div>
</div>

{% endblock %}

todo/templates/edit.html
{%extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{f.as_p}}


    <button type="submit">Confirm</button>
</form>

{% endblock %}

todo/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                <h1><u>TO-DO</u></h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <form method="POST" class="p-3 shadow">
    {% csrf_token %}
            <div class="form-group">
  <input type="text" name="task" class="form-control" placeholder="Enter Taskname"></div>
            <br>
             <div class="form-group">
  <input type="text" name="priority"  class="form-control" placeholder="Enter the priority"></div>
<br>
             <div class="form-group">
  <input type="date" name="date" class="form-control" placeholder="Enter the date"></div>
<br>

  <input type="submit" class="btn btn-success">
</form>
</div>

        <div class="col-md-6">
            <h4>Task to be completed</h4>
       {% for i in task1 %}
<div class="shadow card">

  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.priority}}</p>
      <p class="card-text">{{i.date}}</p>
    <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-danger">Done</a>
    <a href="{% url 'todoapp:update' i.id %}" class="btn btn-success">Update</a>
  </div>
</div>
            <br>{% endfor %}
        </div></div>
</div>

{% endblock %}

todo/templates/update.html
{%extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task-update
        </div>
        <div class="card-body">
            <form method="POST">
    {% csrf_token %}
    {{form.as_p}}


    <button type="submit">Confirm</button>
</form>
        </div>
    </div>
</div>




{% endblock %}